# -*- coding: utf-8 -*-
"""suma de extremos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_oQBbuy5suQ8caU7z4LGRV_Yh8f_AM2
"""

def suma(n1,n2): # O(n)
  imp,par=0,0 # O(1)
  while(n1<=n2): # O(n)
    if(n1%2==0): # O(n)
      par+=n1 # O(n))
    else: # O(n)
      imp+=n1 # O(n)
    n1+=1 # O(n)
  print(imp) # O(1)
  print(par) # O(1)
#ecuación de la función: 7 O(n) + 3 O(1)
suma(4,14) # O(log n)
